"""update unique const in cart items

Revision ID: 0fbe46b1469d
Revises: 4e8e09f7b249
Create Date: 2026-06-09 14:42:49.098536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fbe46b1469d'
down_revision: Union[str, Sequence[str], None] = '4e8e09f7b249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_cart_product_store', 'cart_items', ['cart_id', 'product_id', 'store_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_cart_product_store', 'cart_items', type_='unique')
    # ### end Alembic commands ###
