"""add total price and total amount

Revision ID: 212577341f83
Revises: 5693e513b979
Create Date: 2026-06-10 12:28:20.423844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212577341f83'
down_revision: Union[str, Sequence[str], None] = '5693e513b979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_amount')
    op.drop_column('order_items', 'total_price')
    # ### end Alembic commands ###
