"""add store id in cartItem

Revision ID: 4e8e09f7b249
Revises: 8c25ceefd569
Create Date: 2026-06-09 13:55:37.946629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8e09f7b249'
down_revision: Union[str, Sequence[str], None] = '8c25ceefd569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('store_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_cart_items_store_id'), 'cart_items', ['store_id'], unique=False)
    op.create_foreign_key(None, 'cart_items', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_index(op.f('ix_cart_items_store_id'), table_name='cart_items')
    op.drop_column('cart_items', 'store_id')
    # ### end Alembic commands ###
