"""store id key to order item

Revision ID: 5693e513b979
Revises: 0fbe46b1469d
Create Date: 2026-06-10 11:36:53.690607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5693e513b979'
down_revision: Union[str, Sequence[str], None] = '0fbe46b1469d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('store_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_order_items_store_id'), 'order_items', ['store_id'], unique=False)
    op.create_foreign_key(None, 'order_items', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_index(op.f('ix_order_items_store_id'), table_name='order_items')
    op.drop_column('order_items', 'store_id')
    # ### end Alembic commands ###
