"""remove unit price from cart item

Revision ID: a7f2dcad110f
Revises: a6791fea5e41
Create Date: 2026-06-10 14:35:03.570190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f2dcad110f'
down_revision: Union[str, Sequence[str], None] = 'a6791fea5e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'unit_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
