"""add intent id to payment

Revision ID: c70b40cf2361
Revises: 817e2cf477d8
Create Date: 2026-06-24 11:33:53.398727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70b40cf2361'
down_revision: Union[str, Sequence[str], None] = '817e2cf477d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('intent_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'intent_id')
    # ### end Alembic commands ###
