"""edit primary key

Revision ID: d15a012d5cda
Revises: 972c13e61986
Create Date: 2026-06-10 13:20:38.701245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15a012d5cda'
down_revision: Union[str, Sequence[str], None] = '972c13e61986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_order_product_store', 'order_items', ['order_id', 'product_id', 'store_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_order_product_store', 'order_items', type_='unique')
    # ### end Alembic commands ###
